---
- name: configure vagrant machine
  hosts: 127.0.0.1
  connection: local
  remote_user: vagrant
  sudo: yes
  tasks:
  - name: install git
    yum: name=git state=latest
  - name: install mysql
    yum: name=mysql state=latest
  - name: install docker
    yum: name=docker state=latest
  - name: ensure docker is started
    service: name=docker state=started
  - name: download pip install script
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /home/vagrant/get-pip.py
  - name: install pip
    command: python /home/vagrant/get-pip.py
  - name: install docker-py via pip
    pip: name=docker-py state=latest
  - name: install latest version of six via pip
    # this addresses a compatibility issue with docker-py and the version of six installed by the ansible rpm
    pip: name=six state=latest
    # TODO: fix issue described at https://jpetazzo.github.io/2014/01/29/docker-device-mapper-resize/  / http://unpoucode.blogspot.ca/2015/06/docker-and-devicemappers-thinpool-in.html
    # sudo lvreduce -L4G /dev/VolGroup00/LogVol00
    # sudo lvextend -L4G /dev/VolGroup00/docker-pool
    # above commands resize the volume to deal with thinpool issue - can be forced?

  #- name: install inclusivedesign / php docker image
  #  docker:
  #    docker_api_version: 1.18
  #    name: idrc-php
  #    image: inclusivedesign/php
  #    state: reloaded
